### ISSUE TITLE
Angular 2 webpack links

### ISSUE THREAD

**Issue by damienbod** [d3viant0ne/awesome-webpack#12]
Thanks for this cool repo. Would you be interested in angular 2 webpack links?

https://github.com/AngularClass/awesome-angular2#webpack

Greetings Damien

**Comment by joshwiens** [comment]
@damienbod I was just about to start expanding the examples section. I'll see that those find their way onto the list. Thanks :)

**Comment by damienbod** [comment]
thanks as well

**Comment by damienbod** [comment]
Hi another link missing from the above list:
https://github.com/angular/angular2-seed/
