### ISSUE TITLE
union with webpack docs site

### ISSUE THREAD

**Issue by alexander-akait** [d3viant0ne/awesome-webpack#188]
/cc @snitin315 @chenxsan Maybe we can merge it in webpack docs site - create new page `awesome` put in navigation, so we will have all in one place

**Comment by snitin315** [comment]
This is a nice idea.

**Comment by alexander-akait** [comment]
Let's do it and avoid extra unnecessary repo

**Comment by snitin315** [comment]
I will update 👍

**Comment by anshumanv** [comment]
Fixed in webpack/webpack.js.org#5275
